vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        screenProject:
            uri_prefix: /uploads/projects
            upload_destination: '%kernel.project_dir%/public/uploads/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        pictureDeveloper:
            uri_prefix: /uploads/developerProfil
            upload_destination: '%kernel.project_dir%/public/uploads/developerProfil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


