vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        screenProject:
            uri_prefix: /uploads/projects/thumbnails
            upload_destination: '%kernel.project_dir%/public/uploads/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true

        pictureDeveloper:
            uri_prefix: /uploads/developerProfil
            upload_destination: '%kernel.project_dir%/public/uploads/developerProfil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


